config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  authenticate :user do
    resources :tasks
    root 'tasks#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :title, presence: true

  scope :search, ->(query) { where('title like :search', search: "%#{query}%") if query.present? }
  scope :by_completed, ->(value) { where(completed: value) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password) }
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :update, :destroy, :edit]
  before_action :set_task, only: [:new, :create]

  def index
    @tasks = by_completed_tasks(false)
    @completed_tasks = by_completed_tasks(true)
  end

  def new
  end

  def show
  end

  def create
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render new_task_path
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render edit_task_path(@task)
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def by_completed_tasks(value)
    current_user.tasks.by_completed(value).search(params[:search]).order(updated_at: :desc)
  end

  def task_params
    params.require(:task).permit(:title, :completed)
  end

  def find_task
    @task = current_user.tasks.find(params[:id])
  end

  def set_task
    @task = current_user.tasks.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | To-Do
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'shared/navbar'
    .container
      .row
        = yield

app/views/shared/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container-fluid
    = link_to 'To-Do List', root_path, class: 'navbar-brand'
    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.me-auto.mb-2.mb-lg-0
    - if  current_user
      div[style="color:white;padding:20px"]
        = current_user.full_name
      = link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-success'
      = render 'shared/search'

app/views/shared/_search.html.slim
= form_with url: tasks_path, class: 'd-flex' ,method: :get do |form|
  = form.label :search, 'Search for:'
  = form.text_field :search, value: 'Search', class: 'form-control me-2', 'type' => 'search', 'placeholder' =>'Search', 'aria-label' => 'Search'
  = form.button 'Search', class: 'btn btn-outline-success'

app/views/tasks/_form.html.slim
.col-md-6
  = simple_form_for @task do |f|
    p
      = f.input :title
    p
      = f.input :completed
    p
      = f.button :submit

app/views/tasks/_task.html.slim
tr
  td
    span.title
      = task.title
  td
    = link_to task.completed? ? 'Incomplete' : 'Complete', task_path(id: task.id, task: {completed: !task.completed}), method: :patch, class: 'btn btn-primary btn-sm'
  td
    = link_to 'Edit', edit_task_path(task), class: 'btn btn-warning btn-sm'
  td
    = link_to 'Delete', task_path(task), method: :delete, class: 'btn btn-danger btn-sm'

app/views/tasks/edit.html.slim
.col-md-12
  h1
    | Edit Task
= render 'form'

app/views/tasks/index.html.slim
.row.col-sm-6
  table.table.table-bordered
    thead
      tr
        th
          | Incompleted
    tbody
      = render partial: 'task', collection: @tasks, as: :task
.row.col-sm-6
  table.table.table-bordered
    thead
      tr
        th
          | Completed
    tbody
      = render partial: 'task', collection: @completed_tasks, as: :task
= link_to "New Task", new_task_path, class: 'btn btn-success'

app/views/tasks/new.html.slim
.col-md-12
  h1
    | New Task
= render 'form'

app/views/tasks/show.html.slim
.col-md-12
  h1
    | Show Task

app/views/users/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved", count: resource.errors.count, resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    br